version: '3.8'

services:
  culinary-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
    volumes:
      - 4978bbfd323cb4cc2ea87d496802973a8aba91303a08a548cdace2edc515f3bf:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  culinary-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DB_HOST: culinary-db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORd: mysecretpassword
      DB_DATABASE: postgres
    depends_on:
      - culinary-db
    ports:
      - "3000:3000"

  culinary-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - culinary-backend
    ports:
      - "8080:8080"

volumes:
  4978bbfd323cb4cc2ea87d496802973a8aba91303a08a548cdace2edc515f3bf:
    external: true
